name: 'Add a Repo Owner'
description: 'Add a repo owner for a given repository'
inputs:
  repo-name:  # change this as needed
    description: 'What is the name of the repository?'
    required: true
    default: ''
  org-admin-token:
    description: 'Organization admin token with admin:org scope'
    required: true
    default: ''
  new-owner:
    description: 'Handle of the new owner'
    required: true
    default: ''
outputs:
  status:
    description: 'Pass/Fail status'
    
runs:
  using: 'node12'
  main: 'dist/index.js'